### ISSUE TITLE
Missing:  src/github.com/TheThingsNetwork/ttn/api/trace/*

### ISSUE THREAD

**Issue by gregtoth** [TheThingsNetwork/ttn-gateway-connector#23]
$ make
mkdir -p obj/
cc -fPIC -Wall -g -O2 -Isrc -I../paho.mqtt.embedded-c/MQTTClient-C/src -I../paho.mqtt.embedded-c/MQTTPacket/src -Isrc/github.com/gogo/protobuf/protobuf -Isrc/github.com/TheThingsNetwork -DMQTT_TASK  -I../paho.mqtt.embedded-c/MQTTClient-C/src/linux -c src/connector.c -o obj/connector.o
In file included from src/connector.h:16:0,
                 from src/network.h:10,
                 from src/connector.c:5:
src/github.com/TheThingsNetwork/ttn/api/router/router.pb-c.h:22:38: fatal error: ttn/api/trace/trace.pb-c.h: No such file or directory
compilation terminated.
Makefile:39: recipe for target 'obj/connector.o' failed
make: *** [obj/connector.o] Error 1

**Comment by gregtoth** [comment]
Looks like this was introduced in last commit 189b7d369ced67801efa376899f6b36b443acf5c when ```#include "ttn/api/trace/trace.pb-c.h"``` was added to src/github.com/TheThingsNetwork/ttn/api/router/router.pb-c.h line 22.

**Comment by johanstokking** [comment]
Confirmed, will fix

**Comment by johanstokking** [comment]
Closed by https://github.com/TheThingsNetwork/ttn-gateway-connector/commit/02f3184bff3ea6193c9af0f8dfbcc0734d37c354
