### ISSUE TITLE
Implementations using this library

### ISSUE THREAD

**Issue by ralphtheninja** [TheThingsNetwork/ttn-gateway-connector#24]
Are there any implementations using this lib that you can use out of the box? I guess I'm looking for an implementation that would replace `./poly_pkt_fwd` used in e.g. https://github.com/ttn-zh/ic880a-gateway.git

**Comment by johanstokking** [comment]
@kersing has one (almost) finished. Looping him in here!

Also see this repository https://github.com/kersing/packet_forwarder/tree/master/mp_pkt_fwd/src
