### ISSUE TITLE
Will this also support MQTT over TLS?

### ISSUE THREAD

**Issue by gregtoth** [TheThingsNetwork/ttn-gateway-connector#26]
Will this also support gateway connecting via MQTT over TLS?

**Comment by johanstokking** [comment]
Yes, depending on the platform implementation. In the current Linux implementation, it's not connecting over TLS (see https://github.com/TheThingsNetwork/paho.mqtt.embedded-c/blob/develop/MQTTClient-C/src/linux/MQTTLinux.c#L146-L148), but it's very well possible. This library is platform independent; it simply does a [`NetworkConnect()`](https://github.com/TheThingsNetwork/ttn-gateway-connector/blob/master/src/connector.c#L62)
