### ISSUE TITLE
Proto file absence

### ISSUE THREAD

**Issue by Kiogora** [TheThingsNetwork/ttn-gateway-connector#27]
Hi,

I am trying to implement this on an embedded system, not embedded linux and I want to do it with [nano-pb](https://jpa.kapsi.fi/nanopb/docs/) but I would need the actual proto files to test.

Are they available?

Regards,
Kiogora.

**Comment by johanstokking** [comment]
@Kiogora great, see here https://github.com/TheThingsNetwork/api !
