### ISSUE TITLE
Error configuring protobuf-c

### ISSUE THREAD

**Issue by sympthom** [TheThingsNetwork/ttn-gateway-connector#29]
Hi,

Since there is not that good information of configuring, compiling and installing protobuf and protobuf-c, can you please provide aditional information?

Here is my error message when configuring protobuf-c:

checking google/protobuf/compiler/command_line_interface.h usability... no
checking google/protobuf/compiler/command_line_interface.h presence... no
checking for google/protobuf/compiler/command_line_interface.h... no
ERROR: Installing protobuf-c library. Please check env_protobuf.log

Thanks,

Cheers,
Martin

**Comment by johanstokking** [comment]
This really depends on your environment. Some package managers make it very easy, while you may prefer building from source. We are not planning on adding a manual in this repository.

See here instead: https://github.com/protobuf-c/protobuf-c

**Comment by sympthom** [comment]
Well it really doesn't help when you say it's really easy and then close the issue. I would expect a little more help when you have a person infront of you interested in your project.

I've already done the steps that https://github.com/protobuf-c/protobuf-c points out with the result above.

There are several people experiencing the same problem: https://github.com/protobuf-c/protobuf-c/issues/312

**Comment by sympthom** [comment]
All worked after:

sudo apt-get install protobuf-compiler libprotobuf-dev libprotoc-dev

**Comment by johanstokking** [comment]
> Well it really doesn't help when you say it's really easy and then close the issue

I said that package managers make it very easy, like `apt-get` as you use now, or `brew` on Mac, or one of the other dozens depending on your environment.
