### ISSUE TITLE
Error compiling the test sample

### ISSUE THREAD

**Issue by sympthom** [TheThingsNetwork/ttn-gateway-connector#31]
I'm trying to compile test.c and get some errors. What am I doing wrong?

root@gateway:/home/ubuntu/ttn-gateway-connector# make test
LD_LIBRARY_PATH=bin:/usr/local/lib/ ./bin/ttn-gateway-connector_test
connecting...
connect failed: -1
Makefile:57: recipe for target 'test' failed
make: *** [test] Error 255
root@gateway:/home/ubuntu/ttn-gateway-connector# cd src
root@gateway:/home/ubuntu/ttn-gateway-connector/src# make test
cc     test.c   -o test
In file included from connector.h:15:0,
                 from test.c:10:
github.com/TheThingsNetwork/ttn/api/gateway/gateway.pb-c.h:17:58: fatal error: github.com/gogo/protobuf/gogoproto/gogo.pb-c.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'test' failed
make: *** [test] Error 1
root@gateway:/home/ubuntu/ttn-gateway-connector/src# cd ..
root@gateway:/home/ubuntu/ttn-gateway-connector# make ./src/test
cc -fPIC -Wall -g -O2 -Isrc -I../paho.mqtt.embedded-c/MQTTClient-C/src -I../paho.mqtt.embedded-c/MQTTPacket/src -Isrc/github.com/gogo/protobuf/protobuf -Isrc/github.com/TheThingsNetwork -DMQTT_TASK  -I../paho.mqtt.embedded-c/MQTTClient-C/src/linux    src/test.c   -o src/test
/tmp/ccJy4YED.o: In function `main':
/home/ubuntu/ttn-gateway-connector/src/test.c:54: undefined reference to `ttngwc_init'
/home/ubuntu/ttn-gateway-connector/src/test.c:62: undefined reference to `ttngwc_connect'
/home/ubuntu/ttn-gateway-connector/src/test.c:114: undefined reference to `ttngwc_send_uplink'
/home/ubuntu/ttn-gateway-connector/src/test.c:77: undefined reference to `ttngwc_send_status'
/home/ubuntu/ttn-gateway-connector/src/test.c:124: undefined reference to `ttngwc_disconnect'
/home/ubuntu/ttn-gateway-connector/src/test.c:125: undefined reference to `ttngwc_cleanup'
/home/ubuntu/ttn-gateway-connector/src/test.c:65: undefined reference to `ttngwc_cleanup'
/home/ubuntu/ttn-gateway-connector/src/test.c:128: undefined reference to `gateway__status__descriptor'
/home/ubuntu/ttn-gateway-connector/src/test.c:128: undefined reference to `router__uplink_message__descriptor'
/home/ubuntu/ttn-gateway-connector/src/test.c:128: undefined reference to `protocol__rx_metadata__descriptor'
/home/ubuntu/ttn-gateway-connector/src/test.c:128: undefined reference to `lorawan__metadata__descriptor'
/home/ubuntu/ttn-gateway-connector/src/test.c:128: undefined reference to `gateway__rx_metadata__descriptor'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'src/test' failed
make: *** [src/test] Error 1
root@gateway:/home/ubuntu/ttn-gateway-connector#

**Comment by Xecutor** [comment]
`make test` actually compiles and runs the test.
To compile only use `make bin/ttn-gateway-connector_test`
